#!/usr/bin/env python3
"""
Populate DynamoDB with all 70+ sneaker products
Run: python3 populate_dynamodb_full.py
"""
import boto3
import json

# Initialize DynamoDB
dynamodb = boto3.resource('dynamodb', region_name='us-east-2')
table = dynamodb.Table('sneakers-for-less-products')

# All 70+ products
PRODUCTS = [
    # === JORDAN ===
    {"id": "jordan-1", "name": "Air Jordan 1 Retro High OG Chicago", "brand": "Jordan", "category": "Basketball", "sku": "DZ5485-612", "retail_price": 180, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/af53d53d-561f-450a-a483-70a7ceee380f/air-jordan-1-retro-high-og-shoes-Wvcrrd.png", "colorway": "Varsity Red/Black/Sail", "condition": "new", "prices": [{"store": "eBay", "price": 165, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 189, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 195, "condition": "New", "shipping": "$15"}, {"store": "Flight Club", "price": 210, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-1-travis-scott", "name": "Air Jordan 1 Retro High Travis Scott", "brand": "Jordan", "category": "Basketball", "sku": "CD4487-100", "retail_price": 175, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-1-travis-scott.png", "colorway": "Sail/Dark Mocha/University Red", "condition": "new", "prices": [{"store": "eBay", "price": 1450, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 1525, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 1550, "condition": "New", "shipping": "$25"}, {"store": "Flight Club", "price": 1650, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-1-off-white", "name": "Air Jordan 1 Retro High Off-White Chicago", "brand": "Jordan", "category": "Basketball", "sku": "AA3834-101", "retail_price": 190, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-1-off-white.png", "colorway": "White/Black/Varsity Red", "condition": "new", "prices": [{"store": "eBay", "price": 5800, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 6100, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 6250, "condition": "New", "shipping": "$25"}, {"store": "Flight Club", "price": 6500, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-3", "name": "Air Jordan 3 Retro White Cement", "brand": "Jordan", "category": "Basketball", "sku": "DN3707-100", "retail_price": 200, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/0c857b55-3ae6-4f5a-8977-e5ee07f0b50b/air-jordan-3-retro-shoes-vbNvN8.png", "colorway": "White/Fire Red/Cement Grey", "condition": "new", "prices": [{"store": "eBay", "price": 198, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 235, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 240, "condition": "New", "shipping": "$15"}, {"store": "Flight Club", "price": 250, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-4", "name": "Air Jordan 4 Retro Military Black", "brand": "Jordan", "category": "Basketball", "sku": "DH6927-111", "retail_price": 210, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/2cef0fc9-5ca2-48f1-a59d-d5d4c8c85879/air-jordan-4-retro-shoes-hLJlrl.png", "colorway": "White/Black/Neutral Grey", "condition": "new", "prices": [{"store": "eBay", "price": 285, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 310, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 320, "condition": "New", "shipping": "$15"}, {"store": "Flight Club", "price": 335, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-4-travis-scott", "name": "Air Jordan 4 Retro Travis Scott Cactus Jack", "brand": "Jordan", "category": "Basketball", "sku": "308497-406", "retail_price": 225, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-4-travis-scott.png", "colorway": "University Blue/Varsity Red", "condition": "new", "prices": [{"store": "eBay", "price": 985, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 1050, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 1075, "condition": "New", "shipping": "$25"}, {"store": "Flight Club", "price": 1150, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-5", "name": "Air Jordan 5 Retro Fire Red", "brand": "Jordan", "category": "Basketball", "sku": "DA1911-102", "retail_price": 200, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-5-fire-red.png", "colorway": "True White/Fire Red/Black", "condition": "new", "prices": [{"store": "eBay", "price": 185, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 200, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 205, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 215, "condition": "New", "shipping": "$15"}]},
    {"id": "jordan-6", "name": "Air Jordan 6 Retro UNC", "brand": "Jordan", "category": "Basketball", "sku": "384664-410", "retail_price": 200, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-6-unc.png", "colorway": "University Blue/White", "condition": "new", "prices": [{"store": "eBay", "price": 225, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 245, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 255, "condition": "New", "shipping": "$15"}, {"store": "Flight Club", "price": 275, "condition": "New", "shipping": "Free"}]},
    {"id": "jordan-11", "name": "Air Jordan 11 Retro Cherry", "brand": "Jordan", "category": "Basketball", "sku": "CT8012-116", "retail_price": 225, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/0286a185-86c5-4763-b93b-f09860bbd5d4/air-jordan-11-retro-shoes-T5QG6Q.png", "colorway": "White/Varsity Red/Black", "condition": "new", "prices": [{"store": "Foot Locker", "price": 225, "condition": "New", "shipping": "Free"}, {"store": "eBay", "price": 235, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 255, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 260, "condition": "New", "shipping": "$15"}]},
    {"id": "jordan-12", "name": "Air Jordan 12 Retro Playoffs", "brand": "Jordan", "category": "Basketball", "sku": "CT8013-006", "retail_price": 200, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-12-playoffs.png", "colorway": "Black/Varsity Red/White", "condition": "new", "prices": [{"store": "Foot Locker", "price": 200, "condition": "New", "shipping": "Free"}, {"store": "eBay", "price": 215, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 235, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 245, "condition": "New", "shipping": "$15"}]},
    {"id": "jordan-13", "name": "Air Jordan 13 Retro Flint", "brand": "Jordan", "category": "Basketball", "sku": "414571-404", "retail_price": 200, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/jordan-13-flint.png", "colorway": "Navy/Flint Grey/White", "condition": "new", "prices": [{"store": "eBay", "price": 195, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 215, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 225, "condition": "New", "shipping": "$15"}, {"store": "Flight Club", "price": 240, "condition": "New", "shipping": "Free"}]},
    
    # === NIKE LIFESTYLE ===
    {"id": "dunk-low", "name": "Nike Dunk Low Panda", "brand": "Nike", "category": "Lifestyle", "sku": "DD1391-100", "retail_price": 110, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/b1bcb44f-6280-45e6-a7cb-6a1350c940d9/dunk-low-retro-shoes-76KnBL.png", "colorway": "White/Black", "condition": "new", "prices": [{"store": "eBay", "price": 98, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 110, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 115, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 120, "condition": "New", "shipping": "$15"}]},
    {"id": "sb-dunk-low", "name": "Nike SB Dunk Low Pro", "brand": "Nike", "category": "Lifestyle", "sku": "BQ6817-010", "retail_price": 115, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/sb-dunk-low.png", "colorway": "Black/White/Gum", "condition": "new", "prices": [{"store": "Nike", "price": 115, "condition": "New", "shipping": "Free"}, {"store": "eBay", "price": 125, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 155, "condition": "New", "shipping": "$15"}]},
    {"id": "air-force-1", "name": "Nike Air Force 1 '07", "brand": "Nike", "category": "Lifestyle", "sku": "CW2288-111", "retail_price": 115, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/350e7f3a-979a-402b-9396-a7d9ee31dc0b/air-force-1-07-shoes-VTqD9m.png", "colorway": "White/White", "condition": "new", "prices": [{"store": "eBay", "price": 89, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 95, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 115, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 115, "condition": "New", "shipping": "Free"}]},
    {"id": "air-max-1", "name": "Nike Air Max 1", "brand": "Nike", "category": "Lifestyle", "sku": "DH4059-100", "retail_price": 150, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/air-max-1.png", "colorway": "White/University Red/Grey", "condition": "new", "prices": [{"store": "eBay", "price": 125, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 150, "condition": "New", "shipping": "Free"}]},
    {"id": "air-max-90", "name": "Nike Air Max 90", "brand": "Nike", "category": "Running", "sku": "CN8490-100", "retail_price": 130, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/4d2da657-1e06-4d91-952b-0a5bce78e7a0/air-max-90-shoes-kRsBnD.png", "colorway": "White/White/Wolf Grey", "condition": "new", "prices": [{"store": "eBay", "price": 105, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 118, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 130, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 130, "condition": "New", "shipping": "Free"}]},
    {"id": "air-max-95", "name": "Nike Air Max 95", "brand": "Nike", "category": "Running", "sku": "AT9865-001", "retail_price": 185, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/air-max-95.png", "colorway": "Black/White/Anthracite", "condition": "new", "prices": [{"store": "eBay", "price": 155, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 185, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 185, "condition": "New", "shipping": "Free"}]},
    {"id": "air-max-plus", "name": "Nike Air Max Plus TN", "brand": "Nike", "category": "Running", "sku": "604133-050", "retail_price": 175, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/air-max-plus.png", "colorway": "Black/Volt", "condition": "new", "prices": [{"store": "eBay", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 165, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 175, "condition": "New", "shipping": "Free"}]},
    {"id": "cortez", "name": "Nike Cortez", "brand": "Nike", "category": "Lifestyle", "sku": "DN1791-100", "retail_price": 90, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/cortez.png", "colorway": "White/Varsity Red/Royal", "condition": "new", "prices": [{"store": "eBay", "price": 68, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 78, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 90, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 90, "condition": "New", "shipping": "Free"}]},
    {"id": "blazer-mid", "name": "Nike Blazer Mid '77", "brand": "Nike", "category": "Lifestyle", "sku": "BQ6806-100", "retail_price": 105, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/blazer-mid-77.png", "colorway": "White/Black", "condition": "new", "prices": [{"store": "eBay", "price": 78, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 88, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 105, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 105, "condition": "New", "shipping": "Free"}]},
    {"id": "vomero-5", "name": "Nike Zoom Vomero 5", "brand": "Nike", "category": "Running", "sku": "HF1553-001", "retail_price": 180, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/vomero-5.png", "colorway": "Vast Grey/Sail/Black", "condition": "new", "prices": [{"store": "eBay", "price": 165, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 180, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 185, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 195, "condition": "New", "shipping": "$15"}]},
    {"id": "lebron-21", "name": "Nike LeBron 21", "brand": "Nike", "category": "Basketball", "sku": "FN0708-001", "retail_price": 200, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/2c20c0dc-9c6a-4fd8-a8e4-27b80fc5f3a2/lebron-21-basketball-shoes-z6rT0J.png", "colorway": "Black/Metallic Silver", "condition": "new", "prices": [{"store": "eBay", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 188, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 200, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 200, "condition": "New", "shipping": "Free"}]},
    {"id": "kobe-6", "name": "Nike Kobe 6 Protro Grinch", "brand": "Nike", "category": "Basketball", "sku": "CW2190-300", "retail_price": 180, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/kobe-6-protro-grinch.png", "colorway": "Green Apple/Volt/Crimson", "condition": "new", "prices": [{"store": "eBay", "price": 425, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 475, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 490, "condition": "New", "shipping": "$25"}, {"store": "Flight Club", "price": 525, "condition": "New", "shipping": "Free"}]},
    
    # === ADIDAS ===
    {"id": "yeezy-350", "name": "Adidas Yeezy Boost 350 V2 Onyx", "brand": "Adidas", "category": "Lifestyle", "sku": "HQ4540", "retail_price": 230, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/2ed64993d5f74e7393cfaf0500ec806e_9366/Yeezy_Boost_350_V2_Black_HQ4540_01_standard.jpg", "colorway": "Onyx/Onyx/Onyx", "condition": "new", "prices": [{"store": "eBay", "price": 215, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 228, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 235, "condition": "New", "shipping": "$15"}, {"store": "Stadium Goods", "price": 250, "condition": "New", "shipping": "$10"}]},
    {"id": "yeezy-500", "name": "Adidas Yeezy 500 Utility Black", "brand": "Adidas", "category": "Lifestyle", "sku": "F36640", "retail_price": 200, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/yeezy-500.jpg", "colorway": "Utility Black", "condition": "new", "prices": [{"store": "eBay", "price": 185, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 205, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 215, "condition": "New", "shipping": "$15"}, {"store": "Stadium Goods", "price": 230, "condition": "New", "shipping": "$10"}]},
    {"id": "yeezy-700", "name": "Adidas Yeezy 700 V3 Azael", "brand": "Adidas", "category": "Lifestyle", "sku": "FW4980", "retail_price": 200, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/yeezy-700.jpg", "colorway": "Azael/Azael/Azael", "condition": "new", "prices": [{"store": "eBay", "price": 235, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 265, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 275, "condition": "New", "shipping": "$15"}, {"store": "Stadium Goods", "price": 295, "condition": "New", "shipping": "$10"}]},
    {"id": "yeezy-slides", "name": "Adidas Yeezy Slide Onyx", "brand": "Adidas", "category": "Slides", "sku": "HQ6448", "retail_price": 70, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/a2a893d4f9eb4d13b080af1600e75de4_9366/Yeezy_Slide_Black_HQ6448_01_standard.jpg", "colorway": "Onyx", "condition": "new", "prices": [{"store": "eBay", "price": 85, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 98, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 105, "condition": "New", "shipping": "$15"}, {"store": "Stadium Goods", "price": 115, "condition": "New", "shipping": "$10"}]},
    {"id": "ultraboost", "name": "Adidas Ultraboost 22", "brand": "Adidas", "category": "Running", "sku": "GX5460", "retail_price": 190, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/fbaf991a78bc4896a3e9ad7800abcec6_9366/Ultraboost_22_Shoes_Black_GZ0127_01_standard.jpg", "colorway": "Core Black/Cloud White", "condition": "new", "prices": [{"store": "eBay", "price": 125, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 190, "condition": "New", "shipping": "Free"}]},
    {"id": "samba", "name": "Adidas Samba OG", "brand": "Adidas", "category": "Lifestyle", "sku": "B75806", "retail_price": 100, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/7ed0855435194229a525aad6009a0497_9366/Samba_OG_Shoes_White_B75806_01_standard.jpg", "colorway": "Cloud White/Core Black", "condition": "new", "prices": [{"store": "eBay", "price": 88, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 100, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 110, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 115, "condition": "New", "shipping": "$15"}]},
    {"id": "gazelle", "name": "Adidas Gazelle", "brand": "Adidas", "category": "Lifestyle", "sku": "BB5476", "retail_price": 100, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/gazelle.jpg", "colorway": "Core Black/White/Gold", "condition": "new", "prices": [{"store": "eBay", "price": 75, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 85, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 100, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 100, "condition": "New", "shipping": "Free"}]},
    {"id": "campus", "name": "Adidas Campus 00s", "brand": "Adidas", "category": "Lifestyle", "sku": "HQ8708", "retail_price": 110, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/campus-00s.jpg", "colorway": "Core Black/Cloud White", "condition": "new", "prices": [{"store": "eBay", "price": 95, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 110, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 115, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 125, "condition": "New", "shipping": "$15"}]},
    {"id": "forum-low", "name": "Adidas Forum Low", "brand": "Adidas", "category": "Lifestyle", "sku": "FY7756", "retail_price": 110, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/forum-low.jpg", "colorway": "Cloud White/Cloud White", "condition": "new", "prices": [{"store": "eBay", "price": 75, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 88, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 110, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 110, "condition": "New", "shipping": "Free"}]},
    {"id": "nmd", "name": "Adidas NMD R1", "brand": "Adidas", "category": "Lifestyle", "sku": "GZ9256", "retail_price": 150, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/nmd-r1.jpg", "colorway": "Core Black/Core Black", "condition": "new", "prices": [{"store": "eBay", "price": 115, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 135, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 150, "condition": "New", "shipping": "Free"}]},
    {"id": "stan-smith", "name": "Adidas Stan Smith", "brand": "Adidas", "category": "Lifestyle", "sku": "FX5502", "retail_price": 95, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/5c817daa614f4ec9a6c2ab2c00f3d4b0_9366/Stan_Smith_Shoes_White_FX5502_01_standard.jpg", "colorway": "Cloud White/Green", "condition": "new", "prices": [{"store": "eBay", "price": 65, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 78, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 95, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 95, "condition": "New", "shipping": "Free"}]},
    
    # === NEW BALANCE ===
    {"id": "new-balance-550", "name": "New Balance 550 White Green", "brand": "New Balance", "category": "Lifestyle", "sku": "BB550WT1", "retail_price": 130, "image": "https://nb.scene7.com/is/image/NB/bb550wt1_nb_02_i", "colorway": "White/Green", "condition": "new", "prices": [{"store": "eBay", "price": 118, "condition": "New", "shipping": "Free"}, {"store": "New Balance", "price": 130, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 142, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 150, "condition": "New", "shipping": "$15"}]},
    {"id": "new-balance-990", "name": "New Balance 990v5 Grey", "brand": "New Balance", "category": "Running", "sku": "M990GL5", "retail_price": 185, "image": "https://nb.scene7.com/is/image/NB/m990gl5_nb_02_i", "colorway": "Grey/Castlerock", "condition": "new", "prices": [{"store": "eBay", "price": 168, "condition": "New", "shipping": "Free"}, {"store": "New Balance", "price": 185, "condition": "New", "shipping": "Free"}, {"store": "Kith", "price": 185, "condition": "New", "shipping": "$10"}, {"store": "StockX", "price": 195, "condition": "New", "shipping": "Free"}]},
    {"id": "new-balance-2002r", "name": "New Balance 2002R Protection Pack", "brand": "New Balance", "category": "Running", "sku": "M2002RDC", "retail_price": 150, "image": "https://nb.scene7.com/is/image/NB/m2002rdc_nb_02_i", "colorway": "Rain Cloud/Phantom", "condition": "new", "prices": [{"store": "New Balance", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "eBay", "price": 185, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 215, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 225, "condition": "New", "shipping": "$15"}]},
    {"id": "new-balance-530", "name": "New Balance 530", "brand": "New Balance", "category": "Running", "sku": "MR530SG", "retail_price": 100, "image": "https://nb.scene7.com/is/image/NB/mr530sg_nb_02_i", "colorway": "White/Silver", "condition": "new", "prices": [{"store": "eBay", "price": 85, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 95, "condition": "New", "shipping": "Free"}, {"store": "New Balance", "price": 100, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 100, "condition": "New", "shipping": "Free"}]},
    {"id": "new-balance-327", "name": "New Balance 327", "brand": "New Balance", "category": "Lifestyle", "sku": "MS327WE", "retail_price": 100, "image": "https://nb.scene7.com/is/image/NB/ms327we_nb_02_i", "colorway": "White/Moonbeam", "condition": "new", "prices": [{"store": "eBay", "price": 78, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 88, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 95, "condition": "New", "shipping": "Free"}, {"store": "New Balance", "price": 100, "condition": "New", "shipping": "Free"}]},
    {"id": "new-balance-1906r", "name": "New Balance 1906R", "brand": "New Balance", "category": "Running", "sku": "M1906RCA", "retail_price": 150, "image": "https://nb.scene7.com/is/image/NB/m1906rca_nb_02_i", "colorway": "Silver/Blue", "condition": "new", "prices": [{"store": "eBay", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "New Balance", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 165, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 175, "condition": "New", "shipping": "$15"}]},
    
    # === ASICS ===
    {"id": "gel-kayano-14", "name": "Asics Gel-Kayano 14", "brand": "Asics", "category": "Running", "sku": "1201A019", "retail_price": 150, "image": "https://images.asics.com/is/image/asics/1201A019_020_SR_RT_GLB", "colorway": "White/Pure Silver", "condition": "new", "prices": [{"store": "eBay", "price": 135, "condition": "New", "shipping": "Free"}, {"store": "Asics", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 155, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 165, "condition": "New", "shipping": "$15"}]},
    {"id": "gel-nyc", "name": "Asics Gel-NYC", "brand": "Asics", "category": "Running", "sku": "1203A280", "retail_price": 150, "image": "https://images.asics.com/is/image/asics/1203A280_020_SR_RT_GLB", "colorway": "Cream/Steel Grey", "condition": "new", "prices": [{"store": "eBay", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "Asics", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 185, "condition": "New", "shipping": "$15"}]},
    {"id": "asics-gel-peake", "name": "Asics Gel-Peake Cricket Shoes", "brand": "Asics", "category": "Cricket", "sku": "1113A003", "retail_price": 140, "image": "https://images.asics.com/is/image/asics/1113A003_100_SR_RT_GLB", "colorway": "White/Black", "condition": "new", "prices": [{"store": "eBay", "price": 105, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 122, "condition": "New", "shipping": "Free"}, {"store": "Cricket Direct", "price": 135, "condition": "New", "shipping": "$15"}, {"store": "Asics", "price": 140, "condition": "New", "shipping": "Free"}]},
    
    # === SALOMON / ON / HOKA ===
    {"id": "salomon-xt6", "name": "Salomon XT-6", "brand": "Salomon", "category": "Running", "sku": "L41737000", "retail_price": 190, "image": "https://www.salomon.com/xt-6.jpg", "colorway": "Black/Black/Phantom", "condition": "new", "prices": [{"store": "eBay", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "Salomon", "price": 190, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 195, "condition": "New", "shipping": "Free"}, {"store": "GOAT", "price": 205, "condition": "New", "shipping": "$15"}]},
    {"id": "on-cloud-x", "name": "On Cloud X 3", "brand": "On", "category": "Running", "sku": "60.98706", "retail_price": 150, "image": "https://www.on-running.com/cloud-x-3.jpg", "colorway": "Black/Asphalt", "condition": "new", "prices": [{"store": "eBay", "price": 128, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 142, "condition": "New", "shipping": "Free"}, {"store": "On", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "Dick's Sporting", "price": 150, "condition": "New", "shipping": "Free"}]},
    {"id": "hoka-bondi-8", "name": "Hoka Bondi 8", "brand": "Hoka", "category": "Running", "sku": "1123202", "retail_price": 165, "image": "https://www.hoka.com/bondi-8.jpg", "colorway": "Black/Black", "condition": "new", "prices": [{"store": "eBay", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 158, "condition": "New", "shipping": "Free"}, {"store": "Hoka", "price": 165, "condition": "New", "shipping": "Free"}, {"store": "Dick's Sporting", "price": 165, "condition": "New", "shipping": "Free"}]},
    
    # === OTHER LIFESTYLE ===
    {"id": "puma-suede", "name": "Puma Suede Classic XXI", "brand": "Puma", "category": "Lifestyle", "sku": "374915-01", "retail_price": 75, "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374915/01/sv01/fnd/PNA/fmt/png", "colorway": "Black/White", "condition": "new", "prices": [{"store": "eBay", "price": 48, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 58, "condition": "New", "shipping": "Free"}, {"store": "Puma", "price": 75, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 75, "condition": "New", "shipping": "Free"}]},
    {"id": "chuck-taylor", "name": "Converse Chuck Taylor All Star High", "brand": "Converse", "category": "Lifestyle", "sku": "M9160", "retail_price": 65, "image": "https://www.converse.com/dw/image/v2/BCZC_PRD/on/demandware.static/-/Sites-cnv-master-catalog/default/dwbf7c3e45/images/a_107/M9160_A_107X1.jpg", "colorway": "Black/White", "condition": "new", "prices": [{"store": "eBay", "price": 42, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 52, "condition": "New", "shipping": "Free"}, {"store": "Converse", "price": 65, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 65, "condition": "New", "shipping": "Free"}]},
    {"id": "crocs-classic", "name": "Crocs Classic Clog", "brand": "Crocs", "category": "Slides", "sku": "10001", "retail_price": 55, "image": "https://www.crocs.com/classic-clog.jpg", "colorway": "Black", "condition": "new", "prices": [{"store": "eBay", "price": 38, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 45, "condition": "New", "shipping": "Free"}, {"store": "Crocs", "price": 55, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 55, "condition": "New", "shipping": "Free"}]},
    
    # === SOCCER ===
    {"id": "mercurial", "name": "Nike Mercurial Superfly 9 Elite FG", "brand": "Nike", "category": "Soccer", "sku": "DJ4977-001", "retail_price": 275, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/mercurial-superfly-9-elite.png", "colorway": "Black/Chrome/Hyper Royal", "condition": "new", "prices": [{"store": "eBay", "price": 228, "condition": "New", "shipping": "Free"}, {"store": "Soccer.com", "price": 265, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 275, "condition": "New", "shipping": "Free"}, {"store": "Dick's Sporting", "price": 275, "condition": "New", "shipping": "Free"}]},
    {"id": "mercurial-vapor", "name": "Nike Mercurial Vapor 15 Elite FG", "brand": "Nike", "category": "Soccer", "sku": "DJ4978-040", "retail_price": 250, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/mercurial-vapor-15-elite.png", "colorway": "Barely Green/Blackened Blue", "condition": "new", "prices": [{"store": "eBay", "price": 198, "condition": "New", "shipping": "Free"}, {"store": "Pro Direct Soccer", "price": 235, "condition": "New", "shipping": "$15"}, {"store": "Soccer.com", "price": 250, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 250, "condition": "New", "shipping": "Free"}]},
    {"id": "phantom-gx", "name": "Nike Phantom GX Elite FG", "brand": "Nike", "category": "Soccer", "sku": "DD9465-100", "retail_price": 275, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/phantom-gx-elite.png", "colorway": "White/Bright Crimson", "condition": "new", "prices": [{"store": "eBay", "price": 235, "condition": "New", "shipping": "Free"}, {"store": "Soccer.com", "price": 265, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 275, "condition": "New", "shipping": "Free"}, {"store": "Dick's Sporting", "price": 275, "condition": "New", "shipping": "Free"}]},
    {"id": "tiempo-legend", "name": "Nike Tiempo Legend 10 Elite FG", "brand": "Nike", "category": "Soccer", "sku": "DV4337-100", "retail_price": 250, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/tiempo-legend-10-elite.png", "colorway": "White/Black", "condition": "new", "prices": [{"store": "eBay", "price": 205, "condition": "New", "shipping": "Free"}, {"store": "World Soccer Shop", "price": 238, "condition": "New", "shipping": "$10"}, {"store": "Soccer.com", "price": 250, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 250, "condition": "New", "shipping": "Free"}]},
    {"id": "predator", "name": "Adidas Predator Accuracy.1 FG", "brand": "Adidas", "category": "Soccer", "sku": "GW4559", "retail_price": 250, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/predator-accuracy-1.jpg", "colorway": "Core Black/White/Pink", "condition": "new", "prices": [{"store": "eBay", "price": 198, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 225, "condition": "New", "shipping": "Free"}, {"store": "Soccer.com", "price": 250, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 250, "condition": "New", "shipping": "Free"}]},
    {"id": "copa-mundial", "name": "Adidas Copa Mundial FG", "brand": "Adidas", "category": "Soccer", "sku": "015110", "retail_price": 160, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/copa-mundial.jpg", "colorway": "Black/White", "condition": "new", "prices": [{"store": "eBay", "price": 128, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "Soccer.com", "price": 160, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 160, "condition": "New", "shipping": "Free"}]},
    {"id": "puma-future", "name": "Puma Future Ultimate FG/AG", "brand": "Puma", "category": "Soccer", "sku": "107164-01", "retail_price": 250, "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/107164/01/sv01/fnd/PNA/fmt/png", "colorway": "Puma White/Fire Orchid", "condition": "new", "prices": [{"store": "eBay", "price": 195, "condition": "New", "shipping": "Free"}, {"store": "Pro Direct Soccer", "price": 235, "condition": "New", "shipping": "$15"}, {"store": "Soccer.com", "price": 250, "condition": "New", "shipping": "Free"}, {"store": "Puma", "price": 250, "condition": "New", "shipping": "Free"}]},
    {"id": "puma-king", "name": "Puma King Ultimate FG/AG", "brand": "Puma", "category": "Soccer", "sku": "107097-01", "retail_price": 220, "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/107097/01/sv01/fnd/PNA/fmt/png", "colorway": "Puma Black/Puma White", "condition": "new", "prices": [{"store": "eBay", "price": 175, "condition": "New", "shipping": "Free"}, {"store": "Soccer.com", "price": 210, "condition": "New", "shipping": "Free"}, {"store": "Puma", "price": 220, "condition": "New", "shipping": "Free"}, {"store": "Dick's Sporting", "price": 220, "condition": "New", "shipping": "Free"}]},
    {"id": "new-balance-furon", "name": "New Balance Furon V7+ FG", "brand": "New Balance", "category": "Soccer", "sku": "MSF1FH7", "retail_price": 225, "image": "https://nb.scene7.com/is/image/NB/msf1fh75_nb_02_i", "colorway": "White/Neon Dragonfly", "condition": "new", "prices": [{"store": "eBay", "price": 178, "condition": "New", "shipping": "Free"}, {"store": "Pro Direct Soccer", "price": 210, "condition": "New", "shipping": "$15"}, {"store": "Soccer.com", "price": 225, "condition": "New", "shipping": "Free"}, {"store": "New Balance", "price": 225, "condition": "New", "shipping": "Free"}]},
    
    # === CRICKET ===
    {"id": "puma-one8", "name": "Puma One8 Virat Kohli 19.1 Cricket Shoes", "brand": "Puma", "category": "Cricket", "sku": "105564-01", "retail_price": 180, "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/105564/01/sv01/fnd/IND/fmt/png", "colorway": "White/Black/Gold", "condition": "new", "prices": [{"store": "eBay", "price": 145, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 165, "condition": "New", "shipping": "Free"}, {"store": "Cricket Direct", "price": 175, "condition": "New", "shipping": "$15"}, {"store": "Puma", "price": 180, "condition": "New", "shipping": "Free"}]},
    {"id": "puma-one8-pro", "name": "Puma One8 Pro Cricket Spike", "brand": "Puma", "category": "Cricket", "sku": "105565-02", "retail_price": 200, "image": "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/105565/02/sv01/fnd/IND/fmt/png", "colorway": "Elektro Blue/White", "condition": "new", "prices": [{"store": "eBay", "price": 158, "condition": "New", "shipping": "Free"}, {"store": "Amazon India", "price": 178, "condition": "New", "shipping": "$20"}, {"store": "Cricket Store Online", "price": 190, "condition": "New", "shipping": "$15"}, {"store": "Puma", "price": 200, "condition": "New", "shipping": "Free"}]},
    {"id": "new-balance-ck4040", "name": "New Balance CK4040 V5 Cricket", "brand": "New Balance", "category": "Cricket", "sku": "CK4040W5", "retail_price": 190, "image": "https://nb.scene7.com/is/image/NB/ck4040w5_nb_02_i", "colorway": "White/Blue", "condition": "new", "prices": [{"store": "eBay", "price": 148, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 168, "condition": "New", "shipping": "Free"}, {"store": "Cricket Direct", "price": 182, "condition": "New", "shipping": "$15"}, {"store": "New Balance", "price": 190, "condition": "New", "shipping": "Free"}]},
    {"id": "adidas-22yds", "name": "Adidas 22YDS Cricket Shoes", "brand": "Adidas", "category": "Cricket", "sku": "GW6831", "retail_price": 150, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/22yds-cricket.jpg", "colorway": "Cloud White/Royal Blue", "condition": "new", "prices": [{"store": "eBay", "price": 112, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 132, "condition": "New", "shipping": "Free"}, {"store": "Cricket Direct", "price": 145, "condition": "New", "shipping": "$15"}, {"store": "Adidas", "price": 150, "condition": "New", "shipping": "Free"}]},
    
    # === SLIDES ===
    {"id": "nike-slides", "name": "Nike Victori One Slide", "brand": "Nike", "category": "Slides", "sku": "CN9675-002", "retail_price": 30, "image": "https://static.nike.com/a/images/t_PDP_1280_v1/f_auto,q_auto:eco/victori-one-slides.png", "colorway": "Black/White", "condition": "new", "prices": [{"store": "eBay", "price": 22, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 26, "condition": "New", "shipping": "Free"}, {"store": "Nike", "price": 30, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 30, "condition": "New", "shipping": "Free"}]},
    {"id": "adidas-slides", "name": "Adidas Adilette Comfort Slides", "brand": "Adidas", "category": "Slides", "sku": "GZ5891", "retail_price": 45, "image": "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/adilette-comfort.jpg", "colorway": "Core Black/Cloud White", "condition": "new", "prices": [{"store": "eBay", "price": 32, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 38, "condition": "New", "shipping": "Free"}, {"store": "Adidas", "price": 45, "condition": "New", "shipping": "Free"}, {"store": "Foot Locker", "price": 45, "condition": "New", "shipping": "Free"}]},
    
    # === LUXURY ===
    {"id": "common-projects", "name": "Common Projects Achilles Low", "brand": "Common Projects", "category": "Luxury", "sku": "1528-0506", "retail_price": 450, "image": "https://images.ssense.com/image/upload/b_white,c_lpad/common-projects-achilles-low.jpg", "colorway": "White", "condition": "new", "prices": [{"store": "eBay", "price": 325, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 365, "condition": "New", "shipping": "Free"}, {"store": "SSENSE", "price": 450, "condition": "New", "shipping": "Free"}, {"store": "Mr Porter", "price": 450, "condition": "New", "shipping": "Free"}]},
    {"id": "golden-goose", "name": "Golden Goose Super-Star", "brand": "Golden Goose", "category": "Luxury", "sku": "GMF00102", "retail_price": 595, "image": "https://images.ssense.com/image/upload/b_white,c_lpad/golden-goose-super-star.jpg", "colorway": "White/Black", "condition": "new", "prices": [{"store": "eBay", "price": 425, "condition": "New", "shipping": "Free"}, {"store": "StockX", "price": 475, "condition": "New", "shipping": "Free"}, {"store": "Nordstrom", "price": 595, "condition": "New", "shipping": "Free"}, {"store": "Golden Goose", "price": 595, "condition": "New", "shipping": "Free"}]},
    
    # === DRESS ===
    {"id": "allen-edmonds", "name": "Allen Edmonds Park Avenue Oxford", "brand": "Allen Edmonds", "category": "Dress", "sku": "5615", "retail_price": 395, "image": "https://images.allenedmonds.com/park-avenue-black.jpg", "colorway": "Black", "condition": "new", "prices": [{"store": "eBay", "price": 265, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 328, "condition": "New", "shipping": "Free"}, {"store": "Nordstrom", "price": 395, "condition": "New", "shipping": "Free"}, {"store": "Allen Edmonds", "price": 395, "condition": "New", "shipping": "Free"}]},
    {"id": "cole-haan", "name": "Cole Haan Original Grand Wingtip", "brand": "Cole Haan", "category": "Dress", "sku": "C26469", "retail_price": 150, "image": "https://images.colehaan.com/original-grand-wingtip.jpg", "colorway": "Black/White", "condition": "new", "prices": [{"store": "eBay", "price": 98, "condition": "New", "shipping": "Free"}, {"store": "Amazon", "price": 118, "condition": "New", "shipping": "Free"}, {"store": "Cole Haan", "price": 150, "condition": "New", "shipping": "Free"}, {"store": "Nordstrom", "price": 150, "condition": "New", "shipping": "Free"}]},
]

def populate():
    print(f"Populating DynamoDB with {len(PRODUCTS)} products...\n")
    
    success = 0
    for product in PRODUCTS:
        try:
            item = {
                'id': product['id'],
                'name': product['name'],
                'brand': product['brand'],
                'category': product['category'],
                'sku': product['sku'],
                'retail_price': product['retail_price'],
                'image': product['image'],
                'colorway': product['colorway'],
                'condition': product['condition'],
                'prices': json.dumps(product['prices'])
            }
            table.put_item(Item=item)
            success += 1
            print(f"✓ [{success}] {product['name']}")
        except Exception as e:
            print(f"✗ Error: {product['name']} - {e}")
    
    print(f"\n{'='*50}")
    print(f"DONE! Added {success}/{len(PRODUCTS)} products to DynamoDB")
    print(f"{'='*50}")

if __name__ == "__main__":
    populate()
